<?php declare(strict_types=1);

namespace Sofyco\Types\Enum;

enum Country: string
{
    case AFGHANISTAN = 'AF';
    case ALAND_ISLANDS = 'AX';
    case ALBANIA = 'AL';
    case ALGERIA = 'DZ';
    case AMERICAN_SAMOA = 'AS';
    case ANDORRA = 'AD';
    case ANGOLA = 'AO';
    case ANGUILLA = 'AI';
    case ANTARCTICA = 'AQ';
    case ANTIGUA_AND_BARBUDA = 'AG';
    case ARGENTINA = 'AR';
    case ARMENIA = 'AM';
    case ARUBA = 'AW';
    case AUSTRALIA = 'AU';
    case AUSTRIA = 'AT';
    case AZERBAIJAN = 'AZ';
    case BAHAMAS = 'BS';
    case BAHRAIN = 'BH';
    case BANGLADESH = 'BD';
    case BARBADOS = 'BB';
    case BELARUS = 'BY';
    case BELGIUM = 'BE';
    case BELIZE = 'BZ';
    case BENIN = 'BJ';
    case BERMUDA = 'BM';
    case BHUTAN = 'BT';
    case BOLIVIA = 'BO';
    case BOSNIA_AND_HERZEGOVINA = 'BA';
    case BOTSWANA = 'BW';
    case BRAZIL = 'BR';
    case BRITISH_INDIAN_OCEAN_TERRITORY = 'IO';
    case BRUNEI_DARUSSALAM = 'BN';
    case BULGARIA = 'BG';
    case BURKINA_FASO = 'BF';
    case BURUNDI = 'BI';
    case CABO_VERDE = 'CV';
    case CAMBODIA = 'KH';
    case CAMEROON = 'CM';
    case CANADA = 'CA';
    case CAYMAN_ISLANDS = 'KY';
    case CENTRAL_AFRICAN_REPUBLIC = 'CF';
    case CHAD = 'TD';
    case CHILE = 'CL';
    case CHINA = 'CN';
    case CHRISTMAS_ISLAND = 'CX';
    case COCOS_KEELING_ISLANDS = 'CC';
    case COLOMBIA = 'CO';
    case COMOROS = 'KM';
    case CONGO = 'CG';
    case CONGO_DEMOCRATIC_REPUBLIC = 'CD';
    case COOK_ISLANDS = 'CK';
    case COSTA_RICA = 'CR';
    case COTE_DIVOIRE = 'CI';
    case CROATIA = 'HR';
    case CUBA = 'CU';
    case CURACAO = 'CW';
    case CYPRUS = 'CY';
    case CZECHIA = 'CZ';
    case DENMARK = 'DK';
    case DJIBOUTI = 'DJ';
    case DOMINICA = 'DM';
    case DOMINICAN_REPUBLIC = 'DO';
    case ECUADOR = 'EC';
    case EGYPT = 'EG';
    case EL_SALVADOR = 'SV';
    case EQUATORIAL_GUINEA = 'GQ';
    case ERITREA = 'ER';
    case ESTONIA = 'EE';
    case ESWATINI = 'SZ';
    case ETHIOPIA = 'ET';
    case FALKLAND_ISLANDS = 'FK';
    case FAROE_ISLANDS = 'FO';
    case FIJI = 'FJ';
    case FINLAND = 'FI';
    case FRANCE = 'FR';
    case FRENCH_GUIANA = 'GF';
    case FRENCH_POLYNESIA = 'PF';
    case FRENCH_SOUTHERN_TERRITORIES = 'TF';
    case GABON = 'GA';
    case GAMBIA = 'GM';
    case GEORGIA = 'GE';
    case GERMANY = 'DE';
    case GHANA = 'GH';
    case GIBRALTAR = 'GI';
    case GREECE = 'GR';
    case GREENLAND = 'GL';
    case GRENADA = 'GD';
    case GUADELOUPE = 'GP';
    case GUAM = 'GU';
    case GUATEMALA = 'GT';
    case GUERNSEY = 'GG';
    case GUINEA = 'GN';
    case GUINEA_BISSAU = 'GW';
    case GUYANA = 'GY';
    case HAITI = 'HT';
    case HEARD_ISLAND_AND_MCDONALD_ISLANDS = 'HM';
    case HOLY_SEE = 'VA';
    case HONDURAS = 'HN';
    case HONG_KONG = 'HK';
    case HUNGARY = 'HU';
    case ICELAND = 'IS';
    case INDIA = 'IN';
    case INDONESIA = 'ID';
    case IRAN = 'IR';
    case IRAQ = 'IQ';
    case IRELAND = 'IE';
    case ISLE_OF_MAN = 'IM';
    case ISRAEL = 'IL';
    case ITALY = 'IT';
    case JAMAICA = 'JM';
    case JAPAN = 'JP';
    case JERSEY = 'JE';
    case JORDAN = 'JO';
    case KAZAKHSTAN = 'KZ';
    case KENYA = 'KE';
    case KIRIBATI = 'KI';
    case KOREA_NORTH = 'KP';
    case KOREA_SOUTH = 'KR';
    case KUWAIT = 'KW';
    case KYRGYZSTAN = 'KG';
    case LAO_PEOPLES_DEMOCRATIC_REPUBLIC = 'LA';
    case LATVIA = 'LV';
    case LEBANON = 'LB';
    case LESOTHO = 'LS';
    case LIBERIA = 'LR';
    case LIBYA = 'LY';
    case LIECHTENSTEIN = 'LI';
    case LITHUANIA = 'LT';
    case LUXEMBOURG = 'LU';
    case MACAO = 'MO';
    case MADAGASCAR = 'MG';
    case MALAWI = 'MW';
    case MALAYSIA = 'MY';
    case MALDIVES = 'MV';
    case MALI = 'ML';
    case MALTA = 'MT';
    case MARSHALL_ISLANDS = 'MH';
    case MARTINIQUE = 'MQ';
    case MAURITANIA = 'MR';
    case MAURITIUS = 'MU';
    case MAYOTTE = 'YT';
    case MEXICO = 'MX';
    case MICRONESIA = 'FM';
    case MOLDOVA = 'MD';
    case MONACO = 'MC';
    case MONGOLIA = 'MN';
    case MONTENEGRO = 'ME';
    case MONTSERRAT = 'MS';
    case MOROCCO = 'MA';
    case MOZAMBIQUE = 'MZ';
    case MYANMAR = 'MM';
    case NAMIBIA = 'NA';
    case NAURU = 'NR';
    case NEPAL = 'NP';
    case NETHERLANDS = 'NL';
    case NETHERLANDS_ANTILLES = 'AN';
    case NEW_CALEDONIA = 'NC';
    case NEW_ZEALAND = 'NZ';
    case NICARAGUA = 'NI';
    case NIGER = 'NE';
    case NIGERIA = 'NG';
    case NIUE = 'NU';
    case NORFOLK_ISLAND = 'NF';
    case NORTHERN_MARIANA_ISLANDS = 'MP';
    case NORTH_MACEDONIA = 'MK';
    case NORWAY = 'NO';
    case OMAN = 'OM';
    case PAKISTAN = 'PK';
    case PALAU = 'PW';
    case PALESTINE = 'PS';
    case PANAMA = 'PA';
    case PAPUA_NEW_GUINEA = 'PG';
    case PARAGUAY = 'PY';
    case PERU = 'PE';
    case PHILIPPINES = 'PH';
    case PITCAIRN = 'PN';
    case POLAND = 'PL';
    case PORTUGAL = 'PT';
    case PUERTO_RICO = 'PR';
    case QATAR = 'QA';
    case REUNION = 'RE';
    case ROMANIA = 'RO';
    case RUSSIA = 'RU';
    case RWANDA = 'RW';
    case SAINT_BARTHELEMY = 'BL';
    case SAINT_HELENA = 'SH';
    case SAINT_KITTS_AND_NEVIS = 'KN';
    case SAINT_LUCIA = 'LC';
    case SAINT_MARTIN = 'MF';
    case SAINT_PIERRE_AND_MIQUELON = 'PM';
    case SAINT_VINCENT_AND_THE_GRENADINES = 'VC';
    case SAMOA = 'WS';
    case SAN_MARINO = 'SM';
    case SAO_TOME_AND_PRINCIPE = 'ST';
    case SAUDI_ARABIA = 'SA';
    case SENEGAL = 'SN';
    case SERBIA = 'RS';
    case SEYCHELLES = 'SC';
    case SIERRA_LEONE = 'SL';
    case SINGAPORE = 'SG';
    case SINT_MAARTEN = 'SX';
    case SLOVAKIA = 'SK';
    case SLOVENIA = 'SI';
    case SOLOMON_ISLANDS = 'SB';
    case SOMALIA = 'SO';
    case SOUTH_AFRICA = 'ZA';
    case SOUTH_GEORGIA = 'GS';
    case SOUTH_SUDAN = 'SS';
    case SPAIN = 'ES';
    case SRI_LANKA = 'LK';
    case SUDAN = 'SD';
    case SURINAME = 'SR';
    case SWEDEN = 'SE';
    case SWITZERLAND = 'CH';
    case SYRIA = 'SY';
    case TAIWAN = 'TW';
    case TAJIKISTAN = 'TJ';
    case TANZANIA = 'TZ';
    case THAILAND = 'TH';
    case TIMOR_LESTE = 'TL';
    case TOGO = 'TG';
    case TOKELAU = 'TK';
    case TONGA = 'TO';
    case TRINIDAD_AND_TOBAGO = 'TT';
    case TUNISIA = 'TN';
    case TURKEY = 'TR';
    case TURKMENISTAN = 'TM';
    case TURKS_AND_CAICOS_ISLANDS = 'TC';
    case TUVALU = 'TV';
    case UGANDA = 'UG';
    case UKRAINE = 'UA';
    case UNITED_ARAB_EMIRATES = 'AE';
    case UNITED_KINGDOM = 'GB';
    case UNITED_STATES = 'US';
    case URUGUAY = 'UY';
    case UZBEKISTAN = 'UZ';
    case VANUATU = 'VU';
    case VENEZUELA = 'VE';
    case VIETNAM = 'VN';
    case WALLIS_AND_FUTUNA = 'WF';
    case WESTERN_SAHARA = 'EH';
    case YEMEN = 'YE';
    case ZAMBIA = 'ZM';
    case ZIMBABWE = 'ZW';

    private const array COUNTRY_NAME_TO_CODE = [
        Country::ANDORRA->value => ['Andorra'],
        Country::UNITED_ARAB_EMIRATES->value => ['United Arab Emirates'],
        Country::AFGHANISTAN->value => ['Afghanistan'],
        Country::ANTIGUA_AND_BARBUDA->value => ['Antigua'],
        Country::ANGUILLA->value => ['Anguilla'],
        Country::ALBANIA->value => ['Albania'],
        Country::ARMENIA->value => ['Armenia'],
        Country::NETHERLANDS_ANTILLES->value => ['Netherlands Antilles'],
        Country::ANGOLA->value => ['Angola'],
        Country::ANTARCTICA->value => ['Antarctica'],
        Country::ARGENTINA->value => ['Argentina'],
        Country::AMERICAN_SAMOA->value => ['American Samoa'],
        Country::AUSTRIA->value => ['Austria'],
        Country::AUSTRALIA->value => ['Australia'],
        Country::ARUBA->value => ['Aruba'],
        Country::ALAND_ISLANDS->value => ['Aland Islands'],
        Country::AZERBAIJAN->value => ['Azerbaijan'],
        Country::BOSNIA_AND_HERZEGOVINA->value => ['Bosnia and Herzegovina'],
        Country::BARBADOS->value => ['Barbados'],
        Country::BANGLADESH->value => ['Bangladesh'],
        Country::BELGIUM->value => ['Belgium'],
        Country::BURKINA_FASO->value => ['Burkina Faso'],
        Country::BULGARIA->value => ['Bulgaria'],
        Country::BAHRAIN->value => ['Bahrain'],
        Country::BURUNDI->value => ['Burundi'],
        Country::BENIN->value => ['Benin'],
        Country::SAINT_BARTHELEMY->value => ['Saint Barthélemy'],
        Country::BERMUDA->value => ['Bermuda'],
        Country::BRUNEI_DARUSSALAM->value => ['Brunei'],
        Country::BOLIVIA->value => ['Bolivia'],
        Country::BRAZIL->value => ['Brazil'],
        Country::BAHAMAS->value => ['The Bahamas'],
        Country::BHUTAN->value => ['Bhutan'],
        Country::BOTSWANA->value => ['Botswana'],
        Country::BELARUS->value => ['Belarus'],
        Country::BELIZE->value => ['Belize'],
        Country::CANADA->value => ['Canada'],
        Country::COCOS_KEELING_ISLANDS->value => ['Cocos (Keeling) Islands'],
        Country::CONGO_DEMOCRATIC_REPUBLIC->value => ['Democratic Republic of the Congo'],
        Country::CENTRAL_AFRICAN_REPUBLIC->value => ['Central African Republic'],
        Country::CONGO->value => ['Republic of the Congo'],
        Country::SWITZERLAND->value => ['Switzerland'],
        Country::COTE_DIVOIRE->value => ['Côte d\'Ivoire'],
        Country::COOK_ISLANDS->value => ['Cook Islands'],
        Country::CHILE->value => ['Chile'],
        Country::CAMEROON->value => ['Cameroon'],
        Country::CHINA->value => ['China'],
        Country::COLOMBIA->value => ['Colombia'],
        Country::COSTA_RICA->value => ['Costa Rica'],
        Country::CABO_VERDE->value => ['Cape Verde'],
        Country::CURACAO->value => ['Curaçao'],
        Country::CHRISTMAS_ISLAND->value => ['Christmas Island'],
        Country::CYPRUS->value => ['Cyprus'],
        Country::CZECHIA->value => ['Czech Republic'],
        Country::GERMANY->value => ['Germany'],
        Country::DJIBOUTI->value => ['Djibouti'],
        Country::DENMARK->value => ['Denmark'],
        Country::DOMINICA->value => ['Dominica'],
        Country::DOMINICAN_REPUBLIC->value => ['Dominican Republic'],
        Country::ALGERIA->value => ['Algeria'],
        Country::ECUADOR->value => ['Ecuador'],
        Country::ESTONIA->value => ['Estonia'],
        Country::EGYPT->value => ['Egypt'],
        Country::WESTERN_SAHARA->value => ['Western Sahara'],
        Country::ERITREA->value => ['Eritrea'],
        Country::SPAIN->value => ['Spain'],
        Country::ETHIOPIA->value => ['Ethiopia'],
        Country::FINLAND->value => ['Finland'],
        Country::FIJI->value => ['Fiji'],
        Country::FALKLAND_ISLANDS->value => ['Falkland Islands'],
        Country::MICRONESIA->value => ['Federated States of Micronesia'],
        Country::FAROE_ISLANDS->value => ['Faroe Islands'],
        Country::FRANCE->value => ['France'],
        Country::GABON->value => ['Gabon'],
        Country::UNITED_KINGDOM->value => ['United Kingdom'],
        Country::GRENADA->value => ['Grenada'],
        Country::GEORGIA->value => ['Georgia'],
        Country::FRENCH_GUIANA->value => ['French Guiana'],
        Country::GUERNSEY->value => ['Guernsey'],
        Country::GHANA->value => ['Ghana'],
        Country::GIBRALTAR->value => ['Gibraltar'],
        Country::GREENLAND->value => ['Greenland'],
        Country::GAMBIA->value => ['The Gambia'],
        Country::GUINEA->value => ['Guinea'],
        Country::GUADELOUPE->value => ['Guadeloupe'],
        Country::EQUATORIAL_GUINEA->value => ['Equatorial Guinea'],
        Country::GREECE->value => ['Greece'],
        Country::SOUTH_GEORGIA->value => ['South Georgia and the South Sandwich Islands'],
        Country::GUATEMALA->value => ['Guatemala'],
        Country::GUAM->value => ['Guam'],
        Country::GUINEA_BISSAU->value => ['Guinea-Bissau'],
        Country::GUYANA->value => ['Guyana'],
        Country::HONG_KONG->value => ['Hong Kong'],
        Country::HEARD_ISLAND_AND_MCDONALD_ISLANDS->value => ['Heard Island and McDonald Islands'],
        Country::HONDURAS->value => ['Honduras'],
        Country::CROATIA->value => ['Croatia'],
        Country::HAITI->value => ['Haiti'],
        Country::HUNGARY->value => ['Hungary'],
        Country::INDONESIA->value => ['Indonesia'],
        Country::IRELAND->value => ['Ireland'],
        Country::ISRAEL->value => ['Israel'],
        Country::ISLE_OF_MAN->value => ['Isle Of Man'],
        Country::INDIA->value => ['India'],
        Country::BRITISH_INDIAN_OCEAN_TERRITORY->value => ['British Indian Ocean Territory'],
        Country::IRAQ->value => ['Iraq'],
        Country::ICELAND->value => ['Iceland'],
        Country::ITALY->value => ['Italy'],
        Country::JERSEY->value => ['Jersey'],
        Country::JAMAICA->value => ['Jamaica'],
        Country::JORDAN->value => ['Jordan'],
        Country::JAPAN->value => ['Japan'],
        Country::KENYA->value => ['Kenya'],
        Country::KYRGYZSTAN->value => ['Kyrgyzstan'],
        Country::CAMBODIA->value => ['Cambodia'],
        Country::KIRIBATI->value => ['Kiribati'],
        Country::COMOROS->value => ['Comoros'],
        Country::SAINT_KITTS_AND_NEVIS->value => ['Saint Kitts and Nevis'],
        Country::KOREA_SOUTH->value => ['South Korea'],
        Country::KUWAIT->value => ['Kuwait'],
        Country::CAYMAN_ISLANDS->value => ['Cayman Islands'],
        Country::KAZAKHSTAN->value => ['Kazakhstan'],
        Country::LAO_PEOPLES_DEMOCRATIC_REPUBLIC->value => ['Laos'],
        Country::LEBANON->value => ['Lebanon'],
        Country::SAINT_LUCIA->value => ['St. Lucia'],
        Country::LIECHTENSTEIN->value => ['Liechtenstein'],
        Country::SRI_LANKA->value => ['Sri Lanka'],
        Country::LIBERIA->value => ['Liberia'],
        Country::LESOTHO->value => ['Lesotho'],
        Country::LITHUANIA->value => ['Lithuania'],
        Country::LUXEMBOURG->value => ['Luxembourg'],
        Country::LATVIA->value => ['Latvia'],
        Country::LIBYA->value => ['Libya'],
        Country::MOROCCO->value => ['Morocco'],
        Country::MONACO->value => ['Monaco'],
        Country::MOLDOVA->value => ['Moldova'],
        Country::MONTENEGRO->value => ['Montenegro'],
        Country::SAINT_MARTIN->value => ['Saint Martin'],
        Country::MADAGASCAR->value => ['Madagascar'],
        Country::MARSHALL_ISLANDS->value => ['Marshall Islands'],
        Country::NORTH_MACEDONIA->value => ['Macedonia'],
        Country::MALI->value => ['Mali'],
        Country::MYANMAR->value => ['Myanmar'],
        Country::MONGOLIA->value => ['Mongolia'],
        Country::MACAO->value => ['Macau'],
        Country::NORTHERN_MARIANA_ISLANDS->value => ['Northern Mariana Islands'],
        Country::MARTINIQUE->value => ['Martinique'],
        Country::MAURITANIA->value => ['Mauritania'],
        Country::MONTSERRAT->value => ['Montserrat'],
        Country::MALTA->value => ['Malta'],
        Country::MAURITIUS->value => ['Mauritius'],
        Country::MALDIVES->value => ['Maldives'],
        Country::MALAWI->value => ['Malawi'],
        Country::MEXICO->value => ['Mexico'],
        Country::MALAYSIA->value => ['Malaysia'],
        Country::MOZAMBIQUE->value => ['Mozambique'],
        Country::NAMIBIA->value => ['Namibia'],
        Country::NEW_CALEDONIA->value => ['New Caledonia'],
        Country::NIGER->value => ['Niger'],
        Country::NORFOLK_ISLAND->value => ['Norfolk Island'],
        Country::NIGERIA->value => ['Nigeria'],
        Country::NICARAGUA->value => ['Nicaragua'],
        Country::NETHERLANDS->value => ['Netherlands'],
        Country::NORWAY->value => ['Norway'],
        Country::NEPAL->value => ['Nepal'],
        Country::NAURU->value => ['Nauru'],
        Country::NIUE->value => ['Niue'],
        Country::NEW_ZEALAND->value => ['New Zealand'],
        Country::OMAN->value => ['Oman'],
        Country::PANAMA->value => ['Panama'],
        Country::PERU->value => ['Peru'],
        Country::FRENCH_POLYNESIA->value => ['French Polynesia'],
        Country::PAPUA_NEW_GUINEA->value => ['Papua New Guinea'],
        Country::PHILIPPINES->value => ['Philippines'],
        Country::PAKISTAN->value => ['Pakistan'],
        Country::POLAND->value => ['Poland'],
        Country::SAINT_PIERRE_AND_MIQUELON->value => ['Saint Pierre and Miquelon'],
        Country::PITCAIRN->value => ['Pitcairn'],
        Country::PUERTO_RICO->value => ['Puerto Rico'],
        Country::PALESTINE->value => ['Palestine'],
        Country::PORTUGAL->value => ['Portugal'],
        Country::PALAU->value => ['Palau'],
        Country::PARAGUAY->value => ['Paraguay'],
        Country::QATAR->value => ['Qatar'],
        Country::REUNION->value => ['Réunion'],
        Country::ROMANIA->value => ['Romania'],
        Country::SERBIA->value => ['Serbia'],
        Country::RUSSIA->value => ['Russia'],
        Country::RWANDA->value => ['Rwanda'],
        Country::SAUDI_ARABIA->value => ['Saudi Arabia'],
        Country::SOLOMON_ISLANDS->value => ['Solomon Islands'],
        Country::SEYCHELLES->value => ['Seychelles'],
        Country::SWEDEN->value => ['Sweden'],
        Country::SINGAPORE->value => ['Singapore'],
        Country::SAINT_HELENA->value => ['Saint Helena'],
        Country::SLOVENIA->value => ['Slovenia'],
        Country::SLOVAKIA->value => ['Slovakia'],
        Country::SIERRA_LEONE->value => ['Sierra Leone'],
        Country::SAN_MARINO->value => ['San Marino'],
        Country::SENEGAL->value => ['Senegal'],
        Country::SOMALIA->value => ['Somalia'],
        Country::SURINAME->value => ['Suriname'],
        Country::SOUTH_SUDAN->value => ['South Sudan'],
        Country::SAO_TOME_AND_PRINCIPE->value => ['Sao Tome and Principe'],
        Country::EL_SALVADOR->value => ['El Salvador'],
        Country::SINT_MAARTEN->value => ['Sint Maarten'],
        Country::ESWATINI->value => ['Swaziland'],
        Country::TURKS_AND_CAICOS_ISLANDS->value => ['Turks and Caicos Islands'],
        Country::CHAD->value => ['Chad'],
        Country::FRENCH_SOUTHERN_TERRITORIES->value => ['French Southern Territories'],
        Country::TOGO->value => ['Togo'],
        Country::THAILAND->value => ['Thailand'],
        Country::TAJIKISTAN->value => ['Tajikistan'],
        Country::TOKELAU->value => ['Tokelau'],
        Country::TIMOR_LESTE->value => ['Timor-Leste'],
        Country::TURKMENISTAN->value => ['Turkmenistan'],
        Country::TUNISIA->value => ['Tunisia'],
        Country::TONGA->value => ['Tonga'],
        Country::TURKEY->value => ['Turkey'],
        Country::TRINIDAD_AND_TOBAGO->value => ['Trinidad and Tobago'],
        Country::TUVALU->value => ['Tuvalu'],
        Country::TAIWAN->value => ['Taiwan'],
        Country::TANZANIA->value => ['Tanzania'],
        Country::UKRAINE->value => ['Ukraine'],
        Country::UGANDA->value => ['Uganda'],
        Country::UNITED_STATES->value => ['United States'],
        Country::URUGUAY->value => ['Uruguay'],
        Country::UZBEKISTAN->value => ['Uzbekistan'],
        Country::HOLY_SEE->value => ['Vatican City'],
        Country::SAINT_VINCENT_AND_THE_GRENADINES->value => ['Saint Vincent and the Grenadines'],
        Country::VENEZUELA->value => ['Venezuela'],
        Country::VIETNAM->value => ['Vietnam'],
        Country::VANUATU->value => ['Vanuatu'],
        Country::WALLIS_AND_FUTUNA->value => ['Wallis and Futuna'],
        Country::SAMOA->value => ['Samoa'],
        Country::YEMEN->value => ['Yemen'],
        Country::MAYOTTE->value => ['Mayotte'],
        Country::SOUTH_AFRICA->value => ['South Africa'],
        Country::ZAMBIA->value => ['Zambia'],
        Country::ZIMBABWE->value => ['Zimbabwe'],
    ];

    private const array COUNTRY_CODE_TO_LANGUAGE_CODE = [
        Country::AFGHANISTAN->value => Language::PERSIAN,
        Country::ALAND_ISLANDS->value => Language::SWEDISH,
        Country::ALBANIA->value => Language::ALBANIAN,
        Country::ALGERIA->value => Language::ARABIC,
        Country::AMERICAN_SAMOA->value => Language::ENGLISH,
        Country::ANDORRA->value => Language::CATALAN,
        Country::ANGOLA->value => Language::PORTUGUESE,
        Country::ANGUILLA->value => Language::ENGLISH,
        Country::ANTARCTICA->value => Language::ENGLISH,
        Country::ANTIGUA_AND_BARBUDA->value => Language::ENGLISH,
        Country::ARGENTINA->value => Language::SPANISH,
        Country::ARMENIA->value => Language::ARMENIAN,
        Country::ARUBA->value => Language::DUTCH,
        Country::AUSTRALIA->value => Language::ENGLISH,
        Country::AUSTRIA->value => Language::GERMAN,
        Country::AZERBAIJAN->value => Language::AZERBAIJANI,
        Country::BAHAMAS->value => Language::ENGLISH,
        Country::BAHRAIN->value => Language::ARABIC,
        Country::BANGLADESH->value => Language::BENGALI,
        Country::BELARUS->value => Language::BELARUSIAN,
        Country::BELGIUM->value => Language::DUTCH,
        Country::BELIZE->value => Language::ENGLISH,
        Country::BENIN->value => Language::FRENCH,
        Country::BERMUDA->value => Language::ENGLISH,
        Country::BOLIVIA->value => Language::SPANISH,
        Country::BOSNIA_AND_HERZEGOVINA->value => Language::BOSNIAN,
        Country::BOTSWANA->value => Language::ENGLISH,
        Country::BRAZIL->value => Language::PORTUGUESE,
        Country::BRITISH_INDIAN_OCEAN_TERRITORY->value => Language::ENGLISH,
        Country::BRUNEI_DARUSSALAM->value => Language::MALAY,
        Country::BULGARIA->value => Language::BULGARIAN,
        Country::BURKINA_FASO->value => Language::FRENCH,
        Country::BURUNDI->value => Language::FRENCH,
        Country::CABO_VERDE->value => Language::PORTUGUESE,
        Country::CAMBODIA->value => Language::KHMER,
        Country::CAMEROON->value => Language::FRENCH,
        Country::CANADA->value => Language::ENGLISH,
        Country::CAYMAN_ISLANDS->value => Language::ENGLISH,
        Country::CENTRAL_AFRICAN_REPUBLIC->value => Language::FRENCH,
        Country::CHAD->value => Language::FRENCH,
        Country::CHILE->value => Language::SPANISH,
        Country::CHINA->value => Language::CHINESE,
        Country::CHRISTMAS_ISLAND->value => Language::ENGLISH,
        Country::COCOS_KEELING_ISLANDS->value => Language::ENGLISH,
        Country::COLOMBIA->value => Language::SPANISH,
        Country::COMOROS->value => Language::ARABIC,
        Country::CONGO->value => Language::FRENCH,
        Country::CONGO_DEMOCRATIC_REPUBLIC->value => Language::FRENCH,
        Country::COOK_ISLANDS->value => Language::ENGLISH,
        Country::COSTA_RICA->value => Language::SPANISH,
        Country::COTE_DIVOIRE->value => Language::FRENCH,
        Country::CROATIA->value => Language::CROATIAN,
        Country::CURACAO->value => Language::DUTCH,
        Country::CYPRUS->value => Language::GREEK,
        Country::CZECHIA->value => Language::CZECH,
        Country::DENMARK->value => Language::DANISH,
        Country::DJIBOUTI->value => Language::FRENCH,
        Country::DOMINICA->value => Language::ENGLISH,
        Country::DOMINICAN_REPUBLIC->value => Language::SPANISH,
        Country::ECUADOR->value => Language::SPANISH,
        Country::EGYPT->value => Language::ARABIC,
        Country::EL_SALVADOR->value => Language::SPANISH,
        Country::EQUATORIAL_GUINEA->value => Language::SPANISH,
        Country::ERITREA->value => Language::TIGRINYA,
        Country::ESTONIA->value => Language::ESTONIAN,
        Country::ESWATINI->value => Language::ENGLISH,
        Country::ETHIOPIA->value => Language::AMHARIC,
        Country::FALKLAND_ISLANDS->value => Language::ENGLISH,
        Country::FAROE_ISLANDS->value => Language::FAROESE,
        Country::FIJI->value => Language::ENGLISH,
        Country::FINLAND->value => Language::FINNISH,
        Country::FRANCE->value => Language::FRENCH,
        Country::FRENCH_GUIANA->value => Language::FRENCH,
        Country::FRENCH_POLYNESIA->value => Language::FRENCH,
        Country::GABON->value => Language::FRENCH,
        Country::GAMBIA->value => Language::ENGLISH,
        Country::GEORGIA->value => Language::GEORGIAN,
        Country::GERMANY->value => Language::GERMAN,
        Country::GHANA->value => Language::ENGLISH,
        Country::GIBRALTAR->value => Language::ENGLISH,
        Country::GREECE->value => Language::GREEK,
        Country::GREENLAND->value => Language::KALAALLISUT,
        Country::GRENADA->value => Language::ENGLISH,
        Country::GUADELOUPE->value => Language::FRENCH,
        Country::GUAM->value => Language::ENGLISH,
        Country::GUATEMALA->value => Language::SPANISH,
        Country::GUERNSEY->value => Language::ENGLISH,
        Country::GUINEA->value => Language::FRENCH,
        Country::GUINEA_BISSAU->value => Language::PORTUGUESE,
        Country::GUYANA->value => Language::ENGLISH,
        Country::HAITI->value => Language::FRENCH,
        Country::HOLY_SEE->value => Language::ITALIAN,
        Country::HONDURAS->value => Language::SPANISH,
        Country::HONG_KONG->value => Language::CHINESE,
        Country::HUNGARY->value => Language::HUNGARIAN,
        Country::ICELAND->value => Language::ICELANDIC,
        Country::INDIA->value => Language::HINDI,
        Country::INDONESIA->value => Language::INDONESIAN,
        Country::IRAN->value => Language::PERSIAN,
        Country::IRAQ->value => Language::ARABIC,
        Country::IRELAND->value => Language::ENGLISH,
        Country::ISLE_OF_MAN->value => Language::ENGLISH,
        Country::ISRAEL->value => Language::HEBREW,
        Country::ITALY->value => Language::ITALIAN,
        Country::JAMAICA->value => Language::ENGLISH,
        Country::JAPAN->value => Language::JAPANESE,
        Country::JERSEY->value => Language::ENGLISH,
        Country::JORDAN->value => Language::ARABIC,
        Country::KAZAKHSTAN->value => Language::KAZAKH,
        Country::KENYA->value => Language::ENGLISH,
        Country::KIRIBATI->value => Language::ENGLISH,
        Country::KOREA_NORTH->value => Language::KOREAN,
        Country::KOREA_SOUTH->value => Language::KOREAN,
        Country::KUWAIT->value => Language::ARABIC,
        Country::KYRGYZSTAN->value => Language::KIRGHIZ,
        Country::LAO_PEOPLES_DEMOCRATIC_REPUBLIC->value => Language::LAO,
        Country::LATVIA->value => Language::LATVIAN,
        Country::LEBANON->value => Language::ARABIC,
        Country::LESOTHO->value => Language::ENGLISH,
        Country::LIBERIA->value => Language::ENGLISH,
        Country::LIBYA->value => Language::ARABIC,
        Country::LIECHTENSTEIN->value => Language::GERMAN,
        Country::LITHUANIA->value => Language::LITHUANIAN,
        Country::LUXEMBOURG->value => Language::FRENCH,
        Country::MACAO->value => Language::CHINESE,
        Country::MADAGASCAR->value => Language::MALAGASY,
        Country::MALAWI->value => Language::ENGLISH,
        Country::MALAYSIA->value => Language::MALAY,
        Country::MALDIVES->value => Language::DIVEHI,
        Country::MALI->value => Language::FRENCH,
        Country::MALTA->value => Language::MALTESE,
        Country::MARSHALL_ISLANDS->value => Language::ENGLISH,
        Country::MARTINIQUE->value => Language::FRENCH,
        Country::MAURITANIA->value => Language::ARABIC,
        Country::MAURITIUS->value => Language::ENGLISH,
        Country::MAYOTTE->value => Language::FRENCH,
        Country::MEXICO->value => Language::SPANISH,
        Country::MICRONESIA->value => Language::ENGLISH,
        Country::MOLDOVA->value => Language::ROMANIAN,
        Country::MONACO->value => Language::FRENCH,
        Country::MONGOLIA->value => Language::MONGOLIAN,
        Country::MONTENEGRO->value => Language::SERBIAN,
        Country::MONTSERRAT->value => Language::ENGLISH,
        Country::MOROCCO->value => Language::ARABIC,
        Country::MOZAMBIQUE->value => Language::PORTUGUESE,
        Country::MYANMAR->value => Language::BURMESE,
        Country::NAMIBIA->value => Language::ENGLISH,
        Country::NAURU->value => Language::ENGLISH,
        Country::NEPAL->value => Language::NEPALI,
        Country::NETHERLANDS->value => Language::DUTCH,
        Country::NEW_CALEDONIA->value => Language::FRENCH,
        Country::NEW_ZEALAND->value => Language::ENGLISH,
        Country::NICARAGUA->value => Language::SPANISH,
        Country::NIGER->value => Language::FRENCH,
        Country::NIGERIA->value => Language::ENGLISH,
        Country::NIUE->value => Language::ENGLISH,
        Country::NORFOLK_ISLAND->value => Language::ENGLISH,
        Country::NORTHERN_MARIANA_ISLANDS->value => Language::ENGLISH,
        Country::NORTH_MACEDONIA->value => Language::MACEDONIAN,
        Country::NORWAY->value => Language::NORWEGIAN,
        Country::OMAN->value => Language::ARABIC,
        Country::PAKISTAN->value => Language::URDU,
        Country::PALAU->value => Language::ENGLISH,
        Country::PALESTINE->value => Language::ARABIC,
        Country::PANAMA->value => Language::SPANISH,
        Country::PAPUA_NEW_GUINEA->value => Language::ENGLISH,
        Country::PARAGUAY->value => Language::SPANISH,
        Country::PERU->value => Language::SPANISH,
        Country::PHILIPPINES->value => Language::TAGALOG,
        Country::PITCAIRN->value => Language::ENGLISH,
        Country::POLAND->value => Language::POLISH,
        Country::PORTUGAL->value => Language::PORTUGUESE,
        Country::PUERTO_RICO->value => Language::SPANISH,
        Country::QATAR->value => Language::ARABIC,
        Country::REUNION->value => Language::FRENCH,
        Country::ROMANIA->value => Language::ROMANIAN,
        Country::RUSSIA->value => Language::RUSSIAN,
        Country::RWANDA->value => Language::KINYARWANDA,
        Country::SAINT_BARTHELEMY->value => Language::FRENCH,
        Country::SAINT_HELENA->value => Language::ENGLISH,
        Country::SAINT_KITTS_AND_NEVIS->value => Language::ENGLISH,
        Country::SAINT_LUCIA->value => Language::ENGLISH,
        Country::SAINT_MARTIN->value => Language::FRENCH,
        Country::SAINT_PIERRE_AND_MIQUELON->value => Language::FRENCH,
        Country::SAINT_VINCENT_AND_THE_GRENADINES->value => Language::ENGLISH,
        Country::SAMOA->value => Language::SAMOAN,
        Country::SAN_MARINO->value => Language::ITALIAN,
        Country::SAO_TOME_AND_PRINCIPE->value => Language::PORTUGUESE,
        Country::SAUDI_ARABIA->value => Language::ARABIC,
        Country::SENEGAL->value => Language::FRENCH,
        Country::SERBIA->value => Language::SERBIAN,
        Country::SEYCHELLES->value => Language::ENGLISH,
        Country::SIERRA_LEONE->value => Language::ENGLISH,
        Country::SINGAPORE->value => Language::ENGLISH,
        Country::SINT_MAARTEN->value => Language::DUTCH,
        Country::SLOVAKIA->value => Language::SLOVAK,
        Country::SLOVENIA->value => Language::SLOVENIAN,
        Country::SOLOMON_ISLANDS->value => Language::ENGLISH,
        Country::SOMALIA->value => Language::SOMALI,
        Country::SOUTH_AFRICA->value => Language::AFRIKAANS,
        Country::SOUTH_SUDAN->value => Language::ENGLISH,
        Country::SPAIN->value => Language::SPANISH,
        Country::SRI_LANKA->value => Language::SINHALA,
        Country::SUDAN->value => Language::ARABIC,
        Country::SURINAME->value => Language::DUTCH,
        Country::SWEDEN->value => Language::SWEDISH,
        Country::SWITZERLAND->value => Language::GERMAN,
        Country::SYRIA->value => Language::ARABIC,
        Country::TAIWAN->value => Language::CHINESE,
        Country::TAJIKISTAN->value => Language::TAJIK,
        Country::TANZANIA->value => Language::SWAHILI,
        Country::THAILAND->value => Language::THAI,
        Country::TIMOR_LESTE->value => Language::PORTUGUESE,
        Country::TONGA->value => Language::ENGLISH,
        Country::TRINIDAD_AND_TOBAGO->value => Language::ENGLISH,
        Country::TUNISIA->value => Language::ARABIC,
        Country::TURKEY->value => Language::TURKISH,
        Country::TURKS_AND_CAICOS_ISLANDS->value => Language::ENGLISH,
        Country::TUVALU->value => Language::ENGLISH,
        Country::UGANDA->value => Language::ENGLISH,
        Country::UKRAINE->value => Language::UKRAINIAN,
        Country::UNITED_ARAB_EMIRATES->value => Language::ARABIC,
        Country::UNITED_KINGDOM->value => Language::ENGLISH,
        Country::UNITED_STATES->value => Language::ENGLISH,
        Country::URUGUAY->value => Language::SPANISH,
        Country::UZBEKISTAN->value => Language::UZBEK,
        Country::VANUATU->value => Language::BISLAMA,
        Country::VENEZUELA->value => Language::SPANISH,
        Country::VIETNAM->value => Language::VIETNAMESE,
        Country::WALLIS_AND_FUTUNA->value => Language::FRENCH,
        Country::WESTERN_SAHARA->value => Language::ARABIC,
        Country::YEMEN->value => Language::ARABIC,
        Country::ZAMBIA->value => Language::ENGLISH,
        Country::ZIMBABWE->value => Language::ENGLISH,
    ];

    public static function findCountryByName(string $countryName): ?Country
    {
        foreach (self::COUNTRY_NAME_TO_CODE as $countryCode => $names) {
            if (in_array($countryName, $names)) {
                return Country::from($countryCode);
            }
        }

        return null;
    }

    public static function findCountryByLanguage(Language $language): ?Country
    {
        $countryCode = array_search($language, self::COUNTRY_CODE_TO_LANGUAGE_CODE) ?: '';

        return Country::tryFrom($countryCode);
    }

    public static function findLanguageByCountry(Country $country): ?Language
    {
        return self::COUNTRY_CODE_TO_LANGUAGE_CODE[$country->value] ?? null;
    }
}
